version: '1.0'
stages:
 - packaging
steps:
  DownloadMyDeps:
    title: Downloading deps
    stage: packaging
    image: node:9
    working_directory: ./04_volume/nest_example
    commands:
      - ls -lt
      - npm install
  RunMyTests:
    title: Running unit tests
    stage: packaging
    image: node:9
    working_directory: ./04_volume/nest_example
    commands:
      - pwd
      - ls -lt
     # - npm test         
 
