version: '1.0'
stages:
 - packaging
steps:
  PackageMyNodeApp:
    title: Packaging Node application
    stage: packaging
    image: node:latest
    working_directory: ./01_simple_pipeline/nodejs_example
    commands:
      - echo "My Node version is"
      - node --version
      - npm install
  PackageMyPythonApp:
    title: Packaging Python application
    stage: packaging
    image: python:3.10.0b2-alpine3.13
    working_directory: ./01_simple_pipeline/python_example
    commands:
      - echo "My Python version is"
      - python --version
      - pip install .   
